#!/usr/bin/env node
// Regenerates everything that is derived from page content: JSON-LD, hreflang,
// the market-report pages and sitemap.xml.
//
// The site itself stays a plain static site with no deploy-time build. This
// script runs locally and its output is committed, so Render keeps serving
// files straight from the repo.
//
//   npm run build

import { readFileSync, writeFileSync, readdirSync, mkdirSync, existsSync, statSync } from "node:fs";
import { join, dirname, relative } from "node:path";
import { fileURLToPath } from "node:url";

import { breadcrumbs, canonicalOf, faqs, reviews } from "./lib/extract.mjs";
import { escapeHtml } from "./lib/html.mjs";
import { parseFrontMatter, renderMarkdown, splitH1 } from "./lib/markdown.mjs";
import { agency, people, HREFLANG_CLUSTERS, RATING, SITE, SKIP, VLAD_ID, AGENCY_ID } from "./lib/site-data.mjs";
import { breadcrumbNav, page } from "./lib/template.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const START = "  <!-- schema:start · generated by scripts/build.mjs · do not hand-edit -->";
const END = "  <!-- schema:end -->";
const HREF_START = "  <!-- hreflang:start · generated by scripts/build.mjs -->";
const HREF_END = "  <!-- hreflang:end -->";

const log = [];

/* ------------------------------------------------------------------ pages */

function htmlFiles(dir = ROOT) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    if (entry === ".git" || entry === "node_modules" || entry === "scripts" || entry === "content") continue;
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...htmlFiles(full));
    else if (entry.endsWith(".html")) out.push(relative(ROOT, full));
  }
  return out.sort();
}

/* --------------------------------------------------------- market reports */

const CONTENT_DIR = join(ROOT, "content", "market-reports");

function loadPosts() {
  if (!existsSync(CONTENT_DIR)) return [];
  return readdirSync(CONTENT_DIR)
    // `_`-prefixed files and the README are notes, not posts.
    .filter((f) => f.endsWith(".md") && !f.startsWith("_") && f !== "README.md")
    .map((file) => {
      const { data, body } = parseFrontMatter(readFileSync(join(CONTENT_DIR, file), "utf8"));
      const slug = data.slug || file.replace(/\.md$/, "");
      const missing = [];
      for (const key of ["title", "description", "date"]) if (!data[key]) missing.push(key);
      if (missing.length) throw new Error(`content/market-reports/${file}: missing front matter ${missing.join(", ")}`);
      return {
        file,
        slug,
        draft: data.draft === true,
        title: data.title,
        description: data.description,
        date: data.date,
        updated: data.updated || data.date,
        eyebrow: data.eyebrow || "Market Report",
        summary: data.summary || data.description,
        image: data.image || `${SITE}/img/og-windermere-wide.jpg`,
        body,
      };
    })
    .sort((a, b) => (a.date < b.date ? 1 : -1));
}

function postUrl(slug) {
  return `${SITE}/market-reports/${slug}/`;
}

function longDate(iso) {
  const [y, m, d] = iso.split("-").map(Number);
  const months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
  return `${months[m - 1]} ${d}, ${y}`;
}

function renderPost(post) {
  const trail = [
    { name: "Home", href: "/" },
    { name: "Market Reports", href: "/market-reports/" },
    { name: post.title },
  ];
  const body = `${breadcrumbNav(trail)}

    <section class="page-hero">
      <div class="wrap">
        <span class="eyebrow">${escapeHtml(post.eyebrow)}</span>
        <h1>${escapeHtml(post.title)}</h1>
        <p class="lede">${escapeHtml(post.summary)}</p>
        <p class="micro" style="margin-top: 2rem;">Published <time datetime="${post.date}">${longDate(post.date)}</time>${
    post.updated !== post.date ? ` · Updated <time datetime="${post.updated}">${longDate(post.updated)}</time>` : ""
  } · By Vlad Kizlo</p>
      </div>
    </section>

    <section class="section section--tight">
      <div class="wrap grid">
        <div style="grid-column: 2 / span 8;" class="reveal">
        ${renderMarkdown(post.body)}
        </div>
      </div>
    </section>`;

  return page({
    title: post.title,
    description: post.description,
    canonical: postUrl(post.slug),
    ogImage: post.image,
    body,
  });
}

function renderIndex(posts) {
  const trail = [{ name: "Home", href: "/" }, { name: "Market Reports" }];
  const list = posts.length
    ? posts
        .map(
          (p, i) => `        <article class="card card--sm reveal${i % 2 ? " reveal-d1" : ""}" style="grid-column: ${i % 2 ? "7 / span 5" : "1 / span 5"};">
          <div class="caption">
            <p class="micro"><time datetime="${p.date}">${longDate(p.date)}</time></p>
            <h2 class="card__title"><a href="/market-reports/${p.slug}/">${escapeHtml(p.title)}</a></h2>
            <p style="margin-top: 1rem;">${escapeHtml(p.summary)}</p>
            <p style="margin-top: 1.5rem;"><a class="text-link" href="/market-reports/${p.slug}/">Read the report</a></p>
          </div>
        </article>`
        )
        .join("\n")
    : `        <div style="grid-column: 2 / span 8;" class="reveal">
          <p class="lede">The next report is being written. In the meantime, every community guide carries current medians for its own area.</p>
          <p style="margin-top: 2rem;"><a class="text-link" href="/communities/">Browse the community guides</a></p>
        </div>`;

  const body = `${breadcrumbNav(trail)}

    <section class="page-hero">
      <div class="wrap">
        <span class="eyebrow">Market Reports</span>
        <h1>What West Orlando <em>actually did</em> this month.</h1>
        <p class="lede">Medians, inventory and days on market for Windermere, Winter Garden, Horizon West and Clermont, pulled from the MLS and written up in plain language.</p>
      </div>
    </section>

    <section class="section section--tight">
      <div class="wrap editorial-grid">
${list}
      </div>
    </section>`;

  return page({
    title: "West Orlando Market Reports | The Kizlo Team",
    description:
      "Monthly Windermere, Winter Garden, Horizon West and Clermont housing market reports from The Kizlo Team. Medians, inventory and days on market, explained.",
    canonical: `${SITE}/market-reports/`,
    ogImage: `${SITE}/img/og-windermere-wide.jpg`,
    body,
  });
}

function buildMarketReports(posts) {
  const published = posts.filter((p) => !p.draft);
  mkdirSync(join(ROOT, "market-reports"), { recursive: true });
  writeFileSync(join(ROOT, "market-reports", "index.html"), renderIndex(published));
  log.push(`market-reports: index with ${published.length} published post(s)`);

  for (const post of published) {
    const dir = join(ROOT, "market-reports", post.slug);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, "index.html"), renderPost(post));
    log.push(`market-reports: wrote /market-reports/${post.slug}/`);
  }
  for (const post of posts.filter((p) => p.draft)) {
    log.push(`market-reports: DRAFT held back, not published: ${post.file}`);
  }
  return published;
}

/* --------------------------------------------------------- legal pages */

const LEGAL_DIR = join(ROOT, "content", "legal");

function loadLegal() {
  if (!existsSync(LEGAL_DIR)) return [];
  return readdirSync(LEGAL_DIR)
    .filter((f) => f.endsWith(".md") && !f.startsWith("_") && f !== "README.md")
    .map((file) => {
      const { data, body } = parseFrontMatter(readFileSync(join(LEGAL_DIR, file), "utf8"));
      const slug = data.slug || file.replace(/\.md$/, "");
      for (const key of ["title", "description"]) {
        if (!data[key]) throw new Error(`content/legal/${file}: missing front matter ${key}`);
      }
      const { heading, body: rest } = splitH1(body);
      return {
        file,
        slug,
        draft: data.draft === true,
        title: data.title,
        heading: heading || data.title,
        description: data.description,
        eyebrow: data.eyebrow || "Legal",
        body: rest,
      };
    })
    .sort((a, b) => a.slug.localeCompare(b.slug));
}

function buildLegal(docs) {
  const published = docs.filter((d) => !d.draft);
  for (const doc of published) {
    const trail = [{ name: "Home", href: "/" }, { name: doc.heading }];
    const body = `${breadcrumbNav(trail)}

    <section class="page-hero">
      <div class="wrap">
        <span class="eyebrow">${escapeHtml(doc.eyebrow)}</span>
        <h1>${escapeHtml(doc.heading)}</h1>
      </div>
    </section>

    <section class="section section--tight">
      <div class="wrap grid">
        <div style="grid-column: 2 / span 8;" class="prose">
        ${renderMarkdown(doc.body)}
        </div>
      </div>
    </section>`;

    // No CTA band: a sales pitch under a privacy policy reads badly, and these
    // pages exist to be read, not to convert.
    const dir = join(ROOT, doc.slug);
    mkdirSync(dir, { recursive: true });
    writeFileSync(
      join(dir, "index.html"),
      page({
        title: doc.title,
        description: doc.description,
        canonical: `${SITE}/${doc.slug}/`,
        body,
        cta: false,
      })
    );
    log.push(`legal: wrote /${doc.slug}/`);
  }
  for (const doc of docs.filter((d) => d.draft)) log.push(`legal: DRAFT held back: ${doc.file}`);
  return published;
}

/* ------------------------------------------------------------ json-ld */

function graphFor(file, html, posts) {
  const canonical = canonicalOf(html);
  const graph = [agency()];

  if (file === "about/index.html") graph.push(...people());

  const crumbs = breadcrumbs(html);
  if (crumbs && crumbs.length > 1) graph.push({ "@type": "BreadcrumbList", itemListElement: crumbs });

  const questions = faqs(html);
  if (questions.length) graph.push({ "@type": "FAQPage", mainEntity: questions });

  if (file === "reviews/index.html") {
    const found = reviews(html);
    if (found.length) {
      // Only this page carries the rating: it is the one page where the
      // reviews behind the number are on screen.
      graph[0].aggregateRating = { "@type": "AggregateRating", ...RATING };
      graph[0].review = found.map((r) => ({ ...r, itemReviewed: { "@id": AGENCY_ID } }));
      log.push(`reviews: ${found.length} Review nodes + AggregateRating ${RATING.ratingValue}/${RATING.reviewCount}`);
    }
  }

  const post = posts.find((p) => canonical === postUrl(p.slug));
  if (post) {
    graph.push({
      "@type": "BlogPosting",
      "@id": `${postUrl(post.slug)}#post`,
      headline: post.title,
      description: post.description,
      image: post.image,
      datePublished: post.date,
      dateModified: post.updated,
      author: { "@id": VLAD_ID },
      publisher: { "@id": AGENCY_ID },
      mainEntityOfPage: postUrl(post.slug),
      inLanguage: "en-US",
    });
  }

  return { "@context": "https://schema.org", "@graph": graph };
}

function replaceManaged(html, startMark, endMark, replacement) {
  const start = html.indexOf(startMark);
  const end = html.indexOf(endMark);
  if (start !== -1 && end !== -1) {
    return html.slice(0, start) + replacement + html.slice(end + endMark.length);
  }
  return null;
}

function injectSchema(html, graph) {
  const block = `${START}\n  <script type="application/ld+json">\n${JSON.stringify(graph, null, 2)}\n  </script>\n${END}`;

  const replaced = replaceManaged(html, START, END, block);
  if (replaced) return replaced;

  // First run: drop the hand-written blocks and take their place.
  const existing = [...html.matchAll(/[ \t]*<script type="application\/ld\+json">[\s\S]*?<\/script>\n?/gi)];
  if (existing.length) {
    let out = html;
    for (let i = existing.length - 1; i >= 0; i -= 1) {
      const m = existing[i];
      out = out.slice(0, m.index) + (i === 0 ? `${block}\n` : "") + out.slice(m.index + m[0].length);
    }
    return out;
  }
  return html.replace(/([ \t]*)<\/head>/i, `${block}\n$1</head>`);
}

function injectHreflang(file, html) {
  const cluster = HREFLANG_CLUSTERS.find((c) => c.pages.includes(file));
  if (!cluster) return html;
  const links = cluster.alternates
    .map((a) => `  <link rel="alternate" hreflang="${a.hreflang}" href="${a.href}">`)
    .join("\n");
  const block = `${HREF_START}\n${links}\n${HREF_END}`;

  const replaced = replaceManaged(html, HREF_START, HREF_END, block);
  if (replaced) return replaced;
  return html.replace(/([ \t]*)(<link rel="canonical"[^>]*>)/i, `$1$2\n${block}`);
}

// Keep the footer in step across every page. Two pages carry slightly
// different legal wording, so this edits in place rather than replacing the
// whole footer, which would rewrite copy nobody asked to change.
function ensureFooter(file, html) {
  let out = html;

  if (!out.includes('<a href="/market-reports/">Market Reports</a>')) {
    out = out.replace(
      /([ \t]*)<li><a href="\/reviews\/">Reviews<\/a><\/li>/,
      '$1<li><a href="/market-reports/">Market Reports</a></li>\n$1<li><a href="/reviews/">Reviews</a></li>'
    );
  }

  // The Ukrainian link is Ukrainian text inside an English page: without a
  // lang attribute a screen reader reads it with English phonetics (WCAG 3.1.2).
  out = out.replace(
    /<li><a href="\/ukrainian-realtor-orlando\/">Українською<\/a><\/li>/,
    '<li><a href="/ukrainian-realtor-orlando/" lang="uk">Українською</a></li>'
  );

  const LEGAL_LINKS =
    '<p class="footer-legal__links"><a href="/privacy-policy/">Privacy Policy</a> · <a href="/terms-of-use/">Terms of Use</a> · <a href="/accessibility/">Accessibility</a></p>';

  if (!out.includes('class="footer-legal__links"')) {
    out = out.replace(
      /([ \t]*)<div class="footer-legal">\n/,
      `$1<div class="footer-legal">\n$1  ${LEGAL_LINKS}\n`
    );
  }
  // 404 has its own stripped-down footer with a different wrapper.
  if (!out.includes('class="footer-legal__links"')) {
    out = out.replace(
      /([ \t]*)<div class="wrap footer-legal"([^>]*)>\n/,
      `$1<div class="wrap footer-legal"$2>\n$1  ${LEGAL_LINKS}\n`
    );
  }

  // The mark carries the words "Equal Housing Opportunity" in its own artwork,
  // so the adjacent text drops them rather than announcing them twice.
  if (!out.includes("equal-housing-opportunity.svg")) {
    out = out.replace(
      /<p>Equal Housing Opportunity(?: ·|\.) Realtor®\.?<\/p>/,
      '<p class="footer-eho"><img src="/img/equal-housing-opportunity.svg" alt="Equal Housing Opportunity" width="260" height="64" loading="lazy" decoding="async"> <span>Realtor®</span></p>'
    );
  }

  // 404 has no Equal Housing line of its own to swap, so the mark is appended.
  if (!out.includes("equal-housing-opportunity.svg") && file === "404.html") {
    out = out.replace(
      /([ \t]*)<\/div>\n([ \t]*)<\/footer>/,
      `$1  <p class="footer-eho"><img src="/img/equal-housing-opportunity.svg" alt="Equal Housing Opportunity" width="260" height="64" loading="lazy" decoding="async"> <span>Realtor®</span></p>\n$1</div>\n$2</footer>`
    );
  }

  if (!out.includes("equal-housing-opportunity.svg")) {
    log.push(`WARNING: ${file} has no Equal Housing Opportunity line to replace`);
  }
  if (!out.includes('class="footer-legal__links"')) {
    log.push(`WARNING: ${file} has no .footer-legal block for the legal links`);
  }
  return out;
}

/* ----------------------------------------------------------- sitemap */

function buildSitemap(files, pages) {
  const previous = new Map();
  const sitemapPath = join(ROOT, "sitemap.xml");
  if (existsSync(sitemapPath)) {
    for (const m of readFileSync(sitemapPath, "utf8").matchAll(/<loc>([^<]+)<\/loc>\s*<lastmod>([^<]+)<\/lastmod>/g)) {
      previous.set(m[1], m[2]);
    }
  }
  const today = new Date().toISOString().slice(0, 10);

  const urls = [];
  for (const file of files) {
    const html = pages.get(file);
    if (/<meta name="robots" content="[^"]*noindex/i.test(html)) continue;
    const canonical = canonicalOf(html);
    if (!canonical) continue;
    urls.push({ loc: canonical, lastmod: previous.get(canonical) || today });
  }
  urls.sort((a, b) => (a.loc === `${SITE}/` ? -1 : b.loc === `${SITE}/` ? 1 : a.loc.localeCompare(b.loc)));

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url><loc>${u.loc}</loc><lastmod>${u.lastmod}</lastmod></url>`).join("\n")}
</urlset>
`;
  writeFileSync(sitemapPath, xml);
  log.push(`sitemap: ${urls.length} URLs`);
  return urls;
}

/* -------------------------------------------------------------- main */

const posts = loadPosts();
const published = buildMarketReports(posts);
buildLegal(loadLegal());

const all = htmlFiles();
const files = all.filter((f) => !SKIP.has(f));
const pages = new Map();

for (const file of files) {
  const original = readFileSync(join(ROOT, file), "utf8");
  let html = ensureFooter(file, original);
  html = injectHreflang(file, html);
  html = injectSchema(html, graphFor(file, html, published));
  pages.set(file, html);
  if (html !== original) {
    writeFileSync(join(ROOT, file), html);
    log.push(`schema: ${file}`);
  }
}

// 404 carries no structured data but still needs the legal footer.
if (all.includes("404.html")) {
  const original = readFileSync(join(ROOT, "404.html"), "utf8");
  const html = ensureFooter("404.html", original);
  if (html !== original) {
    writeFileSync(join(ROOT, "404.html"), html);
    log.push("footer: 404.html");
  }
}

buildSitemap(files, pages);

console.log(log.join("\n"));
console.log(`\nbuild ok · ${files.length} pages`);
